name: Edge release

on:
  push:
    branches:
    - dev

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: "ubuntu:20.04"

    steps:
    - name: Bootstrap
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -yq
        apt-get install -yq git

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: recursive

    - name: Build
      run: setup/ci/build/build-linux.sh
      env:
        EXTERNAL_DATA_URL: ${{ secrets.EXTERNAL_DATA_URL }}
        EXTERNAL_DATA_PASSWORD: ${{ secrets.EXTERNAL_DATA_PASSWORD }}

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-linux
        path: "*.AppImage"
